# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Trigger build'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./console1/console1.sln
    - name: Build
      run: dotnet publish ./console1/console1.sln --no-restore -c Release
    - name: Archive build artifacts
      run: |
        mkdir deploy
        mkdir deploy/console1
        cp -r console1/bin/Release/net8.0/publish/* deploy/console1/

    - name: Commit and push artifacts to another repo 🗃️
      env: 
        GIT_AUTHOR_NAME: deployment-bot
        GIT_AUTHOR_EMAIL: xuebaibai2@hotmail.com
        GIT_COMMITTER_NAME: github-actions
        GIT_COMMITTER_EMAIL: xuebaibai2@hotmail.com
        REPO_URL: https://${{ secrets.DEPLOYMENT_USER }}:${{ secrets.DEPLOYMENT_TOKEN }}@github.com/${{ secrets.TARGET_REPO_OWNER }}/${{ secrets.TARGET_REPO_NAME }}.git
        BUILD_NUMBER: ${{ github.run_number }}
        BRANCH_NAME: deployment/console1-${{ github.run_number }}
      run: |
        echo ${REPO_URL}
        cd deploy
        git init
        git config --global user.name "${GIT_AUTHOR_NAME}"
        git config --global user.email "${GIT_AUTHOR_EMAIL}"
        git checkout -b ${BRANCH_NAME}
        git add .
        git commit -m "Publish Console1 - Build #${BUILD_NUMBER}"
        git remote add origin ${REPO_URL}
        git push --force --set-upstream origin ${BRANCH_NAME}
