# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./console1/console1.sln
    - name: Build
      run: dotnet build ./console1/console1.sln --no-restore

    - name: Archive build artifacts
      run: |
        mkdir -p output
        cp -r home_api/console1/bin/Release/* /output

    - name: Commit and push artifacts to another repo 🗃️
      env: 
        GIT_AUTHOR_NAME: deployment-bot
        GIT_AUTHOR_EMAIL: xuebaibai2@hotmail.com
        GIT_COMMITTER_NAME: github-actions
        GIT_COMMITTER_EMAIL: xuebaibai2@hotmail.com
        REPO_URL: https://${{ secrets.DEPLOYMENT_USER }}:${{ secrets.DEPLOYMENT_TOKEN }}@github.com/<TARGET_REPO_OWNER>/<TARGET_REPO_NAME>.git
      run: |
        cd output
        git init
        git config --global user.name "${GIT_AUTHOR_NAME}"
        git config --global user.email "${GIT_AUTHOR_EMAIL}"
        git add .
        git commit -m "Add build artifacts"
        git remote add origin ${REPO_URL}
        git push --force origin deployment
